#!/bin/bash
bash bash/ETH/0.sh
bash bash/UFL/0.sh
runFR ETH/corrected_jet/PUweight_complete/Mu17/ unweighted/
runFR ETH/corrected_jet/PUweight_complete/Mu17/ fit_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu17/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu17MC/ unweighted/
runFR ETH/corrected_jet/PUweight_complete/Mu17MC/ fit_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu17MC/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40/ unweighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40/ fit_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40MC/ unweighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40MC/ fit_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40MC/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_complete/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17/ unweighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17/ fit_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17MC/ unweighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17MC/ fit_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17MC/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40/ unweighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40/ fit_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40MC/ unweighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40MC/ fit_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40MC/ qcd_weighted/
runFR ETH/corrected_jet/PUweight_runD/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_jet/noPUweight/Mu17/ unweighted/
runFR ETH/corrected_jet/noPUweight/Mu17/ fit_weighted/
runFR ETH/corrected_jet/noPUweight/Mu17/ qcd_weighted/
runFR ETH/corrected_jet/noPUweight/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_jet/noPUweight/Mu17MC/ unweighted/
runFR ETH/corrected_jet/noPUweight/Mu17MC/ fit_weighted/
runFR ETH/corrected_jet/noPUweight/Mu17MC/ qcd_weighted/
runFR ETH/corrected_jet/noPUweight/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_jet/noPUweight/Mu40/ unweighted/
runFR ETH/corrected_jet/noPUweight/Mu40/ fit_weighted/
runFR ETH/corrected_jet/noPUweight/Mu40/ qcd_weighted/
runFR ETH/corrected_jet/noPUweight/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_jet/noPUweight/Mu40MC/ unweighted/
runFR ETH/corrected_jet/noPUweight/Mu40MC/ fit_weighted/
runFR ETH/corrected_jet/noPUweight/Mu40MC/ qcd_weighted/
runFR ETH/corrected_jet/noPUweight/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17/ unweighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17MC/ unweighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17MC/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17MC/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40/ unweighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40MC/ unweighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40MC/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40MC/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_complete/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17/ unweighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17MC/ unweighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17MC/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17MC/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40/ unweighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40MC/ unweighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40MC/ fit_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40MC/ qcd_weighted/
runFR ETH/corrected_jetd0/PUweight_runD/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17/ unweighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17/ fit_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17/ qcd_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17MC/ unweighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17MC/ fit_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17MC/ qcd_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40/ unweighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40/ fit_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40/ qcd_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40MC/ unweighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40MC/ fit_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40MC/ qcd_weighted/
runFR ETH/corrected_jetd0/noPUweight/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17/ unweighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17/ fit_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17MC/ unweighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17MC/ fit_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17MC/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40/ unweighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40/ fit_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40MC/ unweighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40MC/ fit_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40MC/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_complete/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17/ unweighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17/ fit_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17MC/ unweighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17MC/ fit_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17MC/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40/ unweighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40/ fit_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40MC/ unweighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40MC/ fit_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40MC/ qcd_weighted/
runFR ETH/corrected_tot/PUweight_runD/Mu40MC/ qcdwjets_weighted/
runFR ETH/corrected_tot/noPUweight/Mu17/ unweighted/
runFR ETH/corrected_tot/noPUweight/Mu17/ fit_weighted/
runFR ETH/corrected_tot/noPUweight/Mu17/ qcd_weighted/
runFR ETH/corrected_tot/noPUweight/Mu17/ qcdwjets_weighted/
runFR ETH/corrected_tot/noPUweight/Mu17MC/ unweighted/
runFR ETH/corrected_tot/noPUweight/Mu17MC/ fit_weighted/
runFR ETH/corrected_tot/noPUweight/Mu17MC/ qcd_weighted/
runFR ETH/corrected_tot/noPUweight/Mu17MC/ qcdwjets_weighted/
runFR ETH/corrected_tot/noPUweight/Mu40/ unweighted/
runFR ETH/corrected_tot/noPUweight/Mu40/ fit_weighted/
runFR ETH/corrected_tot/noPUweight/Mu40/ qcd_weighted/
runFR ETH/corrected_tot/noPUweight/Mu40/ qcdwjets_weighted/
runFR ETH/corrected_tot/noPUweight/Mu40MC/ unweighted/
runFR ETH/corrected_tot/noPUweight/Mu40MC/ fit_weighted/
runFR ETH/corrected_tot/noPUweight/Mu40MC/ qcd_weighted/
runFR ETH/corrected_tot/noPUweight/Mu40MC/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu17/ unweighted/
runFR ETH/uncorrected/PUweight_complete/Mu17/ fit_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu17/ qcd_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu17/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu17MC/ unweighted/
runFR ETH/uncorrected/PUweight_complete/Mu17MC/ fit_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu17MC/ qcd_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu17MC/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu40/ unweighted/
runFR ETH/uncorrected/PUweight_complete/Mu40/ fit_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu40/ qcd_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu40/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu40MC/ unweighted/
runFR ETH/uncorrected/PUweight_complete/Mu40MC/ fit_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu40MC/ qcd_weighted/
runFR ETH/uncorrected/PUweight_complete/Mu40MC/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu17/ unweighted/
runFR ETH/uncorrected/PUweight_runD/Mu17/ fit_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu17/ qcd_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu17/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu17MC/ unweighted/
runFR ETH/uncorrected/PUweight_runD/Mu17MC/ fit_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu17MC/ qcd_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu17MC/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu40/ unweighted/
runFR ETH/uncorrected/PUweight_runD/Mu40/ fit_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu40/ qcd_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu40/ qcdwjets_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu40MC/ unweighted/
runFR ETH/uncorrected/PUweight_runD/Mu40MC/ fit_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu40MC/ qcd_weighted/
runFR ETH/uncorrected/PUweight_runD/Mu40MC/ qcdwjets_weighted/
runFR ETH/uncorrected/noPUweight/Mu17/ unweighted/
runFR ETH/uncorrected/noPUweight/Mu17/ fit_weighted/
runFR ETH/uncorrected/noPUweight/Mu17/ qcd_weighted/
runFR ETH/uncorrected/noPUweight/Mu17/ qcdwjets_weighted/
runFR ETH/uncorrected/noPUweight/Mu17MC/ unweighted/
runFR ETH/uncorrected/noPUweight/Mu17MC/ fit_weighted/
runFR ETH/uncorrected/noPUweight/Mu17MC/ qcd_weighted/
runFR ETH/uncorrected/noPUweight/Mu17MC/ qcdwjets_weighted/
runFR ETH/uncorrected/noPUweight/Mu40/ unweighted/
runFR ETH/uncorrected/noPUweight/Mu40/ fit_weighted/
runFR ETH/uncorrected/noPUweight/Mu40/ qcd_weighted/
runFR ETH/uncorrected/noPUweight/Mu40/ qcdwjets_weighted/
runFR ETH/uncorrected/noPUweight/Mu40MC/ unweighted/
runFR ETH/uncorrected/noPUweight/Mu40MC/ fit_weighted/
runFR ETH/uncorrected/noPUweight/Mu40MC/ qcd_weighted/
runFR ETH/uncorrected/noPUweight/Mu40MC/ qcdwjets_weighted/




